EXCEPTION IN (Bib_OCLC.py, LINE 396 'viaf_result = requests.get(viaf).json()'): HTTPConnectionPool(host='viaf.org', port=80): Max retries exceeded with url: /viaf/AutoSuggest?query=aFortune%2C%20Mary%2C%20b.%201833%3F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd781984d68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) name: aFortune, Mary, b. 1833?
EXCEPTION IN (Bib_OCLC.py, LINE 288 'viafP_result = requests.get(viafP).json()'): HTTPSConnectionPool(host='viaf.org', port=443): Max retries exceeded with url: /viaf/search?query=local.personalNames+all+%22aFortune%2C%20Mary%2C%20b.%201833%3F%22&sortKeys=holdingscount&recordSchema=BriefVIAF&httpAccept=application/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd781984d68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) name: aFortune, Mary, b. 1833?
EXCEPTION IN (Bib_OCLC.py, LINE 342 'viafC_result = requests.get(viafC).json()'): HTTPSConnectionPool(host='viaf.org', port=443): Max retries exceeded with url: /viaf/search?query=local.corporateNames+all+%22aFortune%2C%20Mary%2C%20b.%201833%3F%22&sortKeys=holdingscount&recordSchema=BriefVIAF&httpAccept=application/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd781984a20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) name: aFortune, Mary, b. 1833?
